using System;
using System.Collections.Generic;
using System.Globalization;

namespace SnipDock.App.Services
{
    public sealed class LocalizationService
    {
        private static readonly IReadOnlyDictionary<string, string> ZhCn = new Dictionary<string, string>
        {
            ["WindowTitle"] = "SnipDock - 管理面板",
            ["PanelTitle"] = "SnipDock - 片段与命令管理面板",
            ["SettingsTooltip"] = "外观与系统设置",
            ["TypeFilterLabel"] = "条目类型",
            ["TagFilterLabel"] = "标签筛选",
            ["AddItem"] = "+ 新建条目",
            ["AddFromClipboard"] = "从剪贴板新建",
            ["TogglePanel"] = "显示 / 隐藏面板",
            ["ResetFloatingPosition"] = "重置悬浮球位置",
            ["SetDataDirectory"] = "设置数据目录",
            ["ExitApp"] = "退出程序",
            ["LegacyInstanceTitle"] = "检测到旧实例在运行",
            ["LegacyInstanceMessage"] = "检测到 PromptShelf 旧版正在运行。\n\nSnipDock 与旧版共享同一数据配置，同时运行可能导致数据冲突。\n\n建议您先退出旧版 PromptShelf 再启动 SnipDock。\n\n是否仍要强制启动 SnipDock？",
            ["DuplicateInstanceTitle"] = "提示",
            ["DuplicateInstanceMessage"] = "SnipDock 已经在后台运行中！",
            ["LoggingInitFailedTitle"] = "严重错误",
            ["LoggingInitFailedMessage"] = "初始化正式数据区日志失败：{0}",
            ["BackupRecoveredTitle"] = "数据文件自动恢复提示",
            ["BackupRecoveredMessage"] = "数据安全提示：检测到您的主数据文件 (prompts.json) 丢失或损坏，系统已自动从最近的备份文件 (prompts.json.bak) 恢复了您的片段数据！\n\n建议您在软件运行稳定后进行二次备份。",
            ["StorageChangedTitle"] = "设置成功",
            ["StorageChangedMessage"] = "数据存储目录已成功修改！为了正式加载新的数据源，软件将自动重新启动。",
            ["UnexpectedErrorTitle"] = "意外错误",
            ["UnexpectedErrorMessage"] = "程序发生异常错误，已记录到日志中：\n{0}",
            ["FatalErrorTitle"] = "致命错误",
            ["FatalErrorMessage"] = "程序发生严重错误并即将关闭，已记录到日志中：\n{0}",
            ["FirstRunTitle"] = "首次配置 SnipDock",
            ["ChangeStorageTitle"] = "更改数据存储位置",
            ["FirstRunGuide"] = "请选择一个文件夹作为 SnipDock 的数据存储目录，所有条目和备份将保存在此文件夹中。",
            ["ChangeStorageGuide"] = "请选择新的数据存储目录，确认后 SnipDock 将切换到新目录并重启。现有用户数据不会被自动移动。",
            ["ChooseFolderFirst"] = "请先选择文件夹",
            ["ConfirmAndStart"] = "确认并开始使用 SnipDock",
            ["SaveAndSwitch"] = "保存并切换目录",
            ["ChooseStorageFolder"] = "选择 SnipDock 数据存储文件夹",
            ["ReselectStorageFolder"] = "重新选择数据存储文件夹",
            ["DirectoryUnavailable"] = "该目录不可用或无写权限：",
            ["EmptyStateTitle"] = "请从左侧列表选择一个条目查看详情",
            ["EmptyStateHint"] = "点击 + 新建条目，或使用 Ctrl+V 从剪贴板创建",
            ["ItemName"] = "条目名称",
            ["ItemType"] = "条目类型",
            ["Tags"] = "标签",
            ["ItemContent"] = "条目内容",
            ["Cancel"] = "取消",
            ["Confirm"] = "确认",
            ["Browse"] = "浏览...",
            ["Close"] = "关闭",
            ["Save"] = "保存",
            ["SettingsTitle"] = "外观与系统设置",
            ["GeneralSettings"] = "常规设置",
            ["TagManagement"] = "标签管理",
            ["About"] = "关于",
            ["Language"] = "界面语言",
            ["Chinese"] = "中文",
            ["English"] = "English",
            ["Theme"] = "系统主题",
            ["DarkMode"] = "深色模式",
            ["LightMode"] = "浅色模式",
            ["AccentColor"] = "应用配色",
            ["Behavior"] = "日常行为习惯",
            ["FocusSearch"] = "打开面板时自动聚焦搜索框",
            ["SelectSearch"] = "打开面板时选中搜索文本",
            ["HideAfterCopy"] = "复制后自动隐藏面板",
            ["HideAfterCopyHint"] = "复制内容后自动收起管理面板，程序仍会在后台运行。",
            ["ClearSearchAfterCopy"] = "复制后清空搜索条件",
            ["StartupSection"] = "常驻后台与自启动",
            ["StartupEnabled"] = "开机自动启动 SnipDock",
            ["StartupHint"] = "登录 Windows 时自动启动 SnipDock，无需手动打开。",
            ["StartupDevHint"] = "* 开发调试模式下（包括 bin\\Debug 或 dotnet run）不建议开启自动启动。建议在发布后的 exe 中开启。",
            ["DataManagement"] = "数据管理与备份",
            ["OpenDataDir"] = "打开数据目录",
            ["OpenLogsDir"] = "打开日志目录",
            ["OpenBackupsDir"] = "打开备份目录",
            ["OpenExportDir"] = "打开导出目录",
            ["ChangeStorageDir"] = "修改存储目录...",
            ["ImportExport"] = "导入与导出数据",
            ["ExportJson"] = "导出全部条目到 JSON 文件...",
            ["ImportJson"] = "从 JSON 文件导入条目...",
            ["RestoreBackup"] = "从自动备份中恢复...",
            ["CreateBackup"] = "立即创建手动备份",
            ["TagPanel"] = "标签操作面板",
            ["SelectedTag"] = "当前选中的标签：",
            ["TargetTag"] = "选中标签 / 输入新名称：",
            ["RenameTag"] = "重命名选中标签...",
            ["MergeTag"] = "确认合并到该标签",
            ["CleanTags"] = "清理无用标签...",
            ["UnusedTags"] = "孤立标签清理",
            ["AboutSnipDock"] = "关于 SnipDock",
            ["AppName"] = "应用名称：",
            ["Version"] = "版本号：",
            ["DataVersion"] = "数据版本：",
            ["Stats"] = "统计信息：",
            ["TotalItems"] = "总条目数: ",
            ["TotalTags"] = "总标签数: ",
            ["SystemPaths"] = "系统路径目录",
            ["StoragePath"] = "数据存储路径:",
            ["LogsPath"] = "日志目录路径:",
            ["BackupsPath"] = "自动备份路径:",
            ["Copy"] = "复制",
            ["CopyContent"] = "复制内容到剪贴板",
            ["Edit"] = "编辑",
            ["Delete"] = "删除",
            ["PinnedTooltip"] = "置顶 / 取消置顶",
            ["FavoriteTooltip"] = "收藏 / 取消收藏",
            ["CreatedAt"] = "创建于 ",
            ["UsageCount"] = "使用次数: ",
            ["LastUsed"] = " 最近使用 ",
            ["NeverUsed"] = "未使用",
            ["All"] = "全部",
            ["AllTags"] = "全部标签",
            ["Command"] = "命令",
            ["Snippet"] = "代码片段",
            ["Note"] = "笔记",
            ["Favorites"] = "收藏",
            ["RecentlyUsed"] = "最近使用",
            ["NewItemTitle"] = "新建条目",
            ["EditItemTitle"] = "编辑条目",
            ["ClipboardItemTitle"] = "添加新内容（来自剪贴板）",
            ["ClipboardDefaultTitle"] = "来自剪贴板的条目",
            ["AiAssistNotice"] = "* 本项目使用 AI 辅助开发（包括 Code Review）",
            ["Saved"] = "已保存",
            ["CopiedContent"] = "已复制 {0} 内容",
            ["CopyFailed"] = "复制失败：{0}",
            ["PathCopied"] = "路径已复制到剪贴板！",
            ["DataDirMissing"] = "数据目录不存在！",
            ["LogsDirMissing"] = "日志目录不存在！",
            ["OpenDataDirFailed"] = "无法打开数据目录：{0}",
            ["OpenLogsDirFailed"] = "无法打开日志目录：{0}",
            ["OpenBackupsDirFailed"] = "无法打开备份目录：{0}",
            ["OpenExportDirFailed"] = "无法打开导出目录：{0}",
            ["OpenedBackups"] = "已打开备份目录",
            ["OpenedData"] = "已打开数据目录",
            ["ExportSuccess"] = "已成功导出 {0} 条！",
            ["ExportFailed"] = "导出失败：{0}",
            ["ImportSuccess"] = "导入成功：新增 {0} 条，跳过 {1} 条重复",
            ["ImportFailed"] = "导入失败：{0}",
            ["ClipboardEmpty"] = "剪贴板中没有可用文本",
            ["ClipboardReadFailed"] = "读取剪贴板失败！",
            ["BackupRestored"] = "备份已成功恢复！",
            ["BackupRestoreFailed"] = "恢复备份失败：{0}",
            ["BackupCreated"] = "手动备份创建成功",
            ["BackupCreateFailed"] = "备份创建失败：{0}",
            ["StartupEnabledToast"] = "已开启开机自动启动！",
            ["StartupDisabledToast"] = "已关闭开机自动启动。",
            ["StartupFailed"] = "设置自启动失败，请检查权限。",
            ["HotkeyFailed"] = "全局热键 Ctrl+Alt+P 注册失败，可能被占用。",
            ["NameRequired"] = "名称不能为空",
            ["ContentRequired"] = "内容不能为空",
            ["SaveFailedMissingItem"] = "保存失败：条目已被删除或不存在",
            ["SaveFailed"] = "保存失败：{0}",
            ["DeleteConfirmTitle"] = "删除确认",
            ["DeleteConfirmMessage"] = "确定要删除条目 “{0}” 吗？",
            ["ExportDialogTitle"] = "导出全部条目到 JSON 文件",
            ["ImportDialogTitle"] = "选择要导入的 JSON 文件",
            ["JsonFileFilter"] = "JSON 文件 (*.json)|*.json",
            ["RestoreDialogTitle"] = "选择要恢复的备份文件",
            ["RestoreConfirmTitle"] = "恢复确认",
            ["RestoreConfirmMessage"] = "恢复备份会用所选备份覆盖当前数据。在执行恢复前，系统自动创建当前数据的备份以防万一。\n\n是否继续恢复备份？",
            ["StartupDevBlockedTitle"] = "无法开启开机自启",
            ["StartupDevBlockedMessage"] = "检测到当前程序处于开发调试目录，开机自启功能已被禁用。建议您在发布并运行正式版可执行文件后再开启此功能。",
            ["TagRenamed"] = "标签重命名成功！",
            ["TagRenameFailed"] = "重命名失败：{0}",
            ["TagMerged"] = "标签合并成功。",
            ["TagMergeFailed"] = "合并失败：{0}",
            ["TagRenameConfirmTitle"] = "确认重命名",
            ["TagRenameConfirmMessage"] = "确定要将标签 '{0}' 重命名为 '{1}' 吗？将同步更新所有包含该标签的条目。",
            ["TagMergeConfirmTitle"] = "确认合并标签",
            ["TagMergeConfirmMessage"] = "确定要将标签 '{0}' 合并到 '{1}' 吗？合并后所有包含 '{0}' 的条目将更新并去除重复标签。",
            ["CleanTagsInfoTitle"] = "标签清理说明",
            ["CleanTagsInfoMessage"] = "在当前版本中，标签是动态从条目内容中提取的。因为没有独立的标签数据表，所有显示的标签都已被至少一个条目所使用，因此不存在孤立的无用标签。",
        };

        private static readonly IReadOnlyDictionary<string, string> EnUs = new Dictionary<string, string>
        {
            ["WindowTitle"] = "SnipDock - Manager",
            ["PanelTitle"] = "SnipDock - Snippets and Commands",
            ["SettingsTooltip"] = "Appearance and system settings",
            ["TypeFilterLabel"] = "Item type",
            ["TagFilterLabel"] = "Tag filter",
            ["AddItem"] = "+ New item",
            ["AddFromClipboard"] = "New from clipboard",
            ["TogglePanel"] = "Show / hide panel",
            ["ResetFloatingPosition"] = "Reset floating ball position",
            ["SetDataDirectory"] = "Set data folder",
            ["ExitApp"] = "Exit SnipDock",
            ["LegacyInstanceTitle"] = "Legacy instance detected",
            ["LegacyInstanceMessage"] = "A legacy PromptShelf instance is still running.\n\nSnipDock may share the same data configuration with the legacy app. Running both at the same time can cause data conflicts.\n\nExit PromptShelf before starting SnipDock.\n\nStart SnipDock anyway?",
            ["DuplicateInstanceTitle"] = "SnipDock",
            ["DuplicateInstanceMessage"] = "SnipDock is already running in the background.",
            ["LoggingInitFailedTitle"] = "Critical error",
            ["LoggingInitFailedMessage"] = "Failed to initialize logging in the data folder: {0}",
            ["BackupRecoveredTitle"] = "Data file recovered",
            ["BackupRecoveredMessage"] = "SnipDock detected that the main data file (prompts.json) was missing or damaged, and recovered your snippets from the latest safety backup (prompts.json.bak).\n\nCreate another backup after confirming the app is running normally.",
            ["StorageChangedTitle"] = "Settings saved",
            ["StorageChangedMessage"] = "The data storage folder was changed. SnipDock will restart to load the new data source.",
            ["UnexpectedErrorTitle"] = "Unexpected error",
            ["UnexpectedErrorMessage"] = "An unexpected error occurred and was written to the log:\n{0}",
            ["FatalErrorTitle"] = "Fatal error",
            ["FatalErrorMessage"] = "A fatal error occurred and SnipDock is about to close. Details were written to the log:\n{0}",
            ["FirstRunTitle"] = "First-time setup",
            ["ChangeStorageTitle"] = "Change storage location",
            ["FirstRunGuide"] = "Choose a folder for SnipDock data. Items and backups will be stored there.",
            ["ChangeStorageGuide"] = "Choose a new data folder. SnipDock will switch to it and restart after confirmation. Existing user data will not be moved automatically.",
            ["ChooseFolderFirst"] = "Choose a folder first",
            ["ConfirmAndStart"] = "Confirm and start SnipDock",
            ["SaveAndSwitch"] = "Save and switch",
            ["ChooseStorageFolder"] = "Choose SnipDock data folder",
            ["ReselectStorageFolder"] = "Choose a new data folder",
            ["DirectoryUnavailable"] = "This folder is unavailable or not writable: ",
            ["EmptyStateTitle"] = "Select an item on the left to view details",
            ["EmptyStateHint"] = "Click + to create an item, or use Ctrl+V from the clipboard",
            ["ItemName"] = "Item name",
            ["ItemType"] = "Item type",
            ["Tags"] = "Tags",
            ["ItemContent"] = "Content",
            ["Cancel"] = "Cancel",
            ["Confirm"] = "Confirm",
            ["Browse"] = "Browse...",
            ["Close"] = "Close",
            ["Save"] = "Save",
            ["SettingsTitle"] = "Appearance and system settings",
            ["GeneralSettings"] = "General",
            ["TagManagement"] = "Tags",
            ["About"] = "About",
            ["Language"] = "Language",
            ["Chinese"] = "Chinese",
            ["English"] = "English",
            ["Theme"] = "Theme",
            ["DarkMode"] = "Dark",
            ["LightMode"] = "Light",
            ["AccentColor"] = "Accent color",
            ["Behavior"] = "Behavior",
            ["FocusSearch"] = "Focus search when opening the panel",
            ["SelectSearch"] = "Select search text when opening the panel",
            ["HideAfterCopy"] = "Hide panel after copy",
            ["HideAfterCopyHint"] = "Collapse the panel after copying. SnipDock keeps running in the background.",
            ["ClearSearchAfterCopy"] = "Clear search after copy",
            ["StartupSection"] = "Background and startup",
            ["StartupEnabled"] = "Start SnipDock with Windows",
            ["StartupHint"] = "Start SnipDock automatically when signing in to Windows.",
            ["StartupDevHint"] = "* Startup is not recommended in debug mode, bin\\Debug, or dotnet run. Enable it from the published exe.",
            ["DataManagement"] = "Data and backups",
            ["OpenDataDir"] = "Open data folder",
            ["OpenLogsDir"] = "Open logs folder",
            ["OpenBackupsDir"] = "Open backups folder",
            ["OpenExportDir"] = "Open export folder",
            ["ChangeStorageDir"] = "Change storage folder...",
            ["ImportExport"] = "Import and export",
            ["ExportJson"] = "Export all items to JSON...",
            ["ImportJson"] = "Import items from JSON...",
            ["RestoreBackup"] = "Restore from backup...",
            ["CreateBackup"] = "Create manual backup",
            ["TagPanel"] = "Tag operations",
            ["SelectedTag"] = "Selected tag:",
            ["TargetTag"] = "Selected tag / new name:",
            ["RenameTag"] = "Rename selected tag...",
            ["MergeTag"] = "Merge into this tag",
            ["CleanTags"] = "Clean unused tags...",
            ["UnusedTags"] = "Unused tag cleanup",
            ["AboutSnipDock"] = "About SnipDock",
            ["AppName"] = "App name:",
            ["Version"] = "Version:",
            ["DataVersion"] = "Data version:",
            ["Stats"] = "Stats:",
            ["TotalItems"] = "Total items: ",
            ["TotalTags"] = "Total tags: ",
            ["SystemPaths"] = "System paths",
            ["StoragePath"] = "Data storage path:",
            ["LogsPath"] = "Logs path:",
            ["BackupsPath"] = "Backups path:",
            ["Copy"] = "Copy",
            ["CopyContent"] = "Copy content to clipboard",
            ["Edit"] = "Edit",
            ["Delete"] = "Delete",
            ["PinnedTooltip"] = "Pin / unpin",
            ["FavoriteTooltip"] = "Favorite / unfavorite",
            ["CreatedAt"] = "Created ",
            ["UsageCount"] = "Used: ",
            ["LastUsed"] = " Last used ",
            ["NeverUsed"] = "Never",
            ["All"] = "All",
            ["AllTags"] = "All tags",
            ["Command"] = "Command",
            ["Snippet"] = "Code snippet",
            ["Note"] = "Note",
            ["Favorites"] = "Favorites",
            ["RecentlyUsed"] = "Recently used",
            ["NewItemTitle"] = "New item",
            ["EditItemTitle"] = "Edit item",
            ["ClipboardItemTitle"] = "Add content from clipboard",
            ["ClipboardDefaultTitle"] = "Clipboard item",
            ["AiAssistNotice"] = "* This project was developed with AI assistance, including code review.",
            ["Saved"] = "Saved",
            ["CopiedContent"] = "{0} content copied.",
            ["CopyFailed"] = "Copy failed: {0}",
            ["PathCopied"] = "Path copied to clipboard.",
            ["DataDirMissing"] = "Data folder does not exist.",
            ["LogsDirMissing"] = "Logs folder does not exist.",
            ["OpenDataDirFailed"] = "Cannot open data folder: {0}",
            ["OpenLogsDirFailed"] = "Cannot open logs folder: {0}",
            ["OpenBackupsDirFailed"] = "Cannot open backups folder: {0}",
            ["OpenExportDirFailed"] = "Cannot open export folder: {0}",
            ["OpenedBackups"] = "Backups folder opened.",
            ["OpenedData"] = "Data folder opened.",
            ["ExportSuccess"] = "Exported {0} items.",
            ["ExportFailed"] = "Export failed: {0}",
            ["ImportSuccess"] = "Import complete: {0} added, {1} duplicates skipped.",
            ["ImportFailed"] = "Import failed: {0}",
            ["ClipboardEmpty"] = "No usable text in the clipboard.",
            ["ClipboardReadFailed"] = "Failed to read the clipboard.",
            ["BackupRestored"] = "Backup restored.",
            ["BackupRestoreFailed"] = "Restore failed: {0}",
            ["BackupCreated"] = "Manual backup created.",
            ["BackupCreateFailed"] = "Backup failed: {0}",
            ["StartupEnabledToast"] = "Startup launch enabled.",
            ["StartupDisabledToast"] = "Startup launch disabled.",
            ["StartupFailed"] = "Failed to update startup settings. Check permissions.",
            ["HotkeyFailed"] = "Global hotkey Ctrl+Alt+P failed to register. It may already be in use.",
            ["NameRequired"] = "Name is required.",
            ["ContentRequired"] = "Content is required.",
            ["SaveFailedMissingItem"] = "Save failed: the item was deleted or no longer exists.",
            ["SaveFailed"] = "Save failed: {0}",
            ["DeleteConfirmTitle"] = "Delete item",
            ["DeleteConfirmMessage"] = "Delete item \"{0}\"?",
            ["ExportDialogTitle"] = "Export all items to JSON",
            ["ImportDialogTitle"] = "Choose a JSON file to import",
            ["JsonFileFilter"] = "JSON files (*.json)|*.json",
            ["RestoreDialogTitle"] = "Choose a backup file to restore",
            ["RestoreConfirmTitle"] = "Restore backup",
            ["RestoreConfirmMessage"] = "Restoring a backup will overwrite current data with the selected backup. SnipDock will create a safety backup first.\n\nContinue?",
            ["StartupDevBlockedTitle"] = "Cannot enable startup launch",
            ["StartupDevBlockedMessage"] = "SnipDock is running from a development/debug folder. Startup launch is disabled here. Enable it from the published executable.",
            ["TagRenamed"] = "Tag renamed.",
            ["TagRenameFailed"] = "Rename failed: {0}",
            ["TagMerged"] = "Tags merged.",
            ["TagMergeFailed"] = "Merge failed: {0}",
            ["TagRenameConfirmTitle"] = "Rename tag",
            ["TagRenameConfirmMessage"] = "Rename tag '{0}' to '{1}'? This updates every item that uses the tag.",
            ["TagMergeConfirmTitle"] = "Merge tags",
            ["TagMergeConfirmMessage"] = "Merge tag '{0}' into '{1}'? Items using '{0}' will be updated and duplicate tags removed.",
            ["CleanTagsInfoTitle"] = "Tag cleanup",
            ["CleanTagsInfoMessage"] = "Tags are derived from items in this version. There is no separate tag table, so every displayed tag is already used by at least one item.",
        };

        public static string DetectDefaultLanguage()
        {
            return CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("zh", StringComparison.OrdinalIgnoreCase)
                ? "zh-CN"
                : "en-US";
        }

        public LocalizedStrings CreateStrings(string? language)
        {
            return new LocalizedStrings(IsChinese(language) ? ZhCn : EnUs);
        }

        public static bool IsChinese(string? language)
        {
            return string.Equals(language, "zh-CN", StringComparison.OrdinalIgnoreCase);
        }

        public static string NormalizeLanguage(string? language)
        {
            if (string.Equals(language, "en-US", StringComparison.OrdinalIgnoreCase)) return "en-US";
            if (string.Equals(language, "zh-CN", StringComparison.OrdinalIgnoreCase)) return "zh-CN";
            return DetectDefaultLanguage();
        }
    }

    public sealed class LocalizedStrings
    {
        private readonly IReadOnlyDictionary<string, string> _strings;

        public LocalizedStrings(IReadOnlyDictionary<string, string> strings)
        {
            _strings = strings;
        }

        public string this[string key] => _strings.TryGetValue(key, out var value) ? value : key;
    }
}
